   printf ("<html>\n");
   printf ("<head>\n");
   printf ("  <title>\n");
   printf ("    Olhar Discente\n");
   printf ("  </title>\n");
   printf ("</head>\n");
   printf ("<body bgcolor='E0FFE0'>\n");
   printf ("<body>\n");
   printf ("  <center>\n");
   printf ("    <hr>\n");
   printf ("    <h1>Olhar Discente</h1>\n");
   printf ("    <hr>\n");
   printf ("    <a href='mailto:renanpassos@poli.ufrj.br?subject=[OLHAR%%20DISCENTE%%20-%%20CONTACTE-NOS]'>Renan Passos</a>\n");
   printf ("    <br><br><br><br>\n");
   printf ("    <table align='center' bgcolor='D0D0FF'>\n");
   printf ("      <form action='dicLogin.cgi' method='post'>\n");
   printf ("        <input type='hidden' name='dicLanguage' value='dicPortuguese'>\n");
   printf ("        <tr>\n");
   printf ("          <td></td>\n");
   printf ("          <td><br></td>\n");
   printf ("          <td></td>\n");
   printf ("          <td></td>\n");
   printf ("          <td></td>\n");
   printf ("        </tr>\n");
   printf ("        <tr>\n");
   printf ("          <td></td>\n");
   printf ("          <td align='right'>Usu&aacuterio:</td>\n");
   printf ("          <td></td>\n");
   printf ("          <td align='left'><input type='text' maxlength='65' name='dicNickname'></td>\n");
   printf ("          <td></td>\n");
   printf ("        </tr>\n");
   printf ("        <tr>\n");
   printf ("          <td></td>\n");
   printf ("          <td align='right'>Senha:</td>\n");
   printf ("          <td></td>\n");
   printf ("          <td align='left'><input type='password' maxlength='127' name='dicPassword'></td>\n");
   printf ("          <td></td>\n");
   printf ("        </tr>\n");
   printf ("        <tr>\n");
   printf ("          <td></td>\n");
   printf ("          <td><br><br><br></td>\n");
   printf ("          <td></td>\n");
   printf ("          <td align='center'><input type='submit' value='Entrar'></td>\n");
   printf ("          <td></td>\n");
   printf ("        </tr>\n");
   printf ("      </form>\n");
   printf ("    </table>  \n");
   printf ("    <br>\n");
   printf ("    <table align='center' style='width:350px'>\n");
   printf ("      <tr>\n");
   printf ("        <td align='left'><a href='dicShowRequestPasswordResetForm.cgi?dicLanguage=dicPortuguese'>Esqueci minha senha</a></td>\n");
   printf ("        <td align='right'><a href='dicShowRequestRegistrationForm.cgi?dicLanguage=dicPortuguese'>Cadastrar</a></td>\n");
   printf ("      </tr>\n");
   printf ("      <tr>\n");
   printf ("        <td align='left'><a href='dicShowLicense.cgi?dicLanguage=dicPortuguese'>Termos de Uso</a></td>\n");
   printf ("        <td align='right'><a href='dicShowWebHelp.cgi?dicLanguage=dicPortuguese'>Ajuda</a></td>\n");
   printf ("      </tr>\n");
   printf ("      <tr>\n");
   printf ("        <td align='left'><a href='dicMain.cgi?dicLanguage=dicEnglish'>English</a></td>\n");
   printf ("      </tr>\n");
   printf ("    </table>  \n");
   printf ("  </center>\n");
   printf ("</body>\n");
   printf ("</html>\n");
   printf ("ÿ
