   printf ("<html>\n");
   printf ("<head>\n");
   printf ("  <title>\n");
   printf ("    Olhar Discente\n");
   printf ("  </title>\n");
   printf ("</head>\n");
   printf ("<body bgcolor='E0FFE0'>\n");
   printf ("<body>\n");
   printf ("  <center>\n");
   printf ("    <hr>\n");
   printf ("    <h1>Olhar Discente</h1>\n");
   printf ("    <hr>\n");
   printf ("    <a href='mailto:renanpassos@poli.ufrj.br?subject=[OLHAR%%20DISCENTE%%20-%%20CONTACTE-NOS]'>Renan Passos</a>\n");
   printf ("    <br><br><br><br>\n");
   printf ("    <table align='center' bgcolor='D0D0FF'>\n");
   printf ("      <form action='dicRequestRegistration.cgi' method='post'>\n");
   printf ("        <input type='hidden' name='dicLanguage' value='dicPortuguese'>\n");
   printf ("        <tr>\n");
   printf ("          <td></td>\n");
   printf ("          <td><br></td>\n");
   printf ("          <td></td>\n");
   printf ("          <td></td>\n");
   printf ("          <td></td>\n");
   printf ("        </tr>\n");
   printf ("        <tr>\n");
   printf ("          <td></td>\n");
   printf ("          <td align='right'>Nome completo:</td>\n");
   printf ("          <td></td>\n");
   printf ("          <td align='left'><input type='text' maxlength='256' size='45' name='dicUserName'></td>\n");
   printf ("          <td></td>\n");
   printf ("        </tr>\n");
   printf ("        <tr>\n");
   printf ("          <td></td>\n");
   printf ("          <td align='right'>Confirma&ccedil&atildeo do nome completo:</td>\n");
   printf ("          <td></td>\n");
   printf ("          <td align='left'><input type='text' maxlength='256' size='45' name='dicUserNameConfirmation'></td>\n");
   printf ("          <td></td>\n");
   printf ("        </tr>\n");
   printf ("        <tr>\n");
   printf ("          <td></td>\n");
   printf ("          <td align='right'>E-mail:</td>\n");
   printf ("          <td></td>\n");
   printf ("          <td align='left'><input type='text' maxlength='1024' size='45' name='dicEmail'></td>\n");
   printf ("          <td></td>\n");
   printf ("        </tr>\n");
   printf ("        <tr>\n");
   printf ("          <td></td>\n");
   printf ("          <td align='right'>Confirma&ccedil&atildeo do E-mail:</td>\n");
   printf ("          <td></td>\n");
   printf ("          <td align='left'><input type='text' maxlength='1024' size='45' name='dicEmailConfirmation'></td>\n");
   printf ("          <td></td>\n");
   printf ("        </tr>\n");
   printf ("        <tr>\n");
   printf ("          <td></td>\n");
   printf ("          <td><br><br><br></td>\n");
   printf ("          <td></td>\n");
   printf ("          <td align='center'><input type='submit' value='Cadastrar'></td>\n");
   printf ("          <td></td>\n");
   printf ("        </tr>\n");
   printf ("      </form>\n");
   printf ("    </table>  \n");
   printf ("    <br>\n");
   printf ("    <table align='center' style='width:350px'>\n");
   printf ("      <tr>\n");
   printf ("        <td align='left'><a href='dicMain.cgi?dicLanguage=dicPortuguese'>P&aacutegina Principal</a></td>\n");
   printf ("        <td align='right'><a href='dicShowLicense.cgi?dicLanguage=dicPortuguese'>Termos de Uso</a></td>\n");
   printf ("      </tr>\n");
   printf ("      <tr>\n");
   printf ("        <td align='left'><a href='dicShowRequestRegistrationForm.cgi?dicLanguage=dicEnglish'>English</a></td>\n");
   printf ("        <td align='right'><a href='dicShowWebHelp.cgi?dicLanguage=dicPortuguese'>Ajuda</a></td>\n");
   printf ("      </tr>\n");
   printf ("    </table>  \n");
   printf ("  </center>\n");
   printf ("</body>\n");
   printf ("</html>\n");
   printf ("ÿ
